spring.application.name=parkingslot
spring.datasource.url=jdbc:postgresql://localhost:5432/parkingslot
spring.datasource.username=postgres
spring.datasource.password=Jefino 1537
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.persist-authorization=true

app.jwt.secret=cGFya2luZ3Nsb3Qtc3VwZXItc2VjdXJlLWp3dC1zZWNyZXQta2V5LTIwMjYtMDE=
app.jwt.expiration-ms=86400000
